/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <amxmisc>
#include <GamePlay_Included/GamePlay_ZM.inc>
#include <fakemeta_util>
#include <hamsandwich>
#include <csred_MsgTool>

#define PLUGIN "Mutation Zombie"
#define VERSION "1.0"
#define AUTHOR "Nguyen Duy Linh"

#define CLASS_NAME "Mutation Zombie"


#define FIRST_MODEL "Mutantion_1"
#define SECOND_MODEL "Mutantion_1"
#define THIRD_MODEL "Mutantion_1"

#define MUTATION_FIRST_CLAW_MODEL "MUTATION_HAND"
#define MUTATION_SECOND_CLAW_MODEL "MUTATION_HAND"
#define MUTATION_THIRD_CLAW_MODEL "MUTATION_HAND"

#define MUTATION_WEAPON_HUD "TMT_HAND"

new const Float:MUTATION_HEALTH[3] = {3000.0, 4500.0, 7000.0}
new const Float:MUTATION_GRAVITY[3] = {0.9, 0.85, 0.8}
new const Float:MUTATION_KNOCKBACK[3] = {3.0, 2.25, 2.0}
new const Float:MUTATION_SPEED[3] = {260.0, 265.0, 270.0}

new const Float:MUTATION_DEFENSIVE[3] = {0.0, 0.0, 12.0}
new const Float:MUTATION_DMG_ARMOR[3] = {52.0, 55.0, 57.0}

#define MUTATION_HEALTH_SKILL 750

new MUTATION_NVG_COLOR[3] = {139, 235, 21}
#define MUTATION_NVG_ALPHA  50
#define MUTATION_NVG_RADIUS 40

#define MUTATION_COST_TYPE 1
#define MUTATION_COST 18500

#define MUTATION_SOUND_DIRECTORY "default_zombie"
#define MUTATION_HUD_CHAR "KE_HUY_DIET"

#define MUTATION_GENDER ZB_GENDER_MALE

#define TASK_DISABLE_SKILL 2000
#define SKILL_TIME 10

#define TASK_CZ_FUNCTION 3000


#define MUTATION_SPEED_UP_SOUND "zombiemod/MUTATION_SPEEDUP.wav"

new iMutationClass


new bool:bInSkill[33]
new iHamCz = 0

enum
{
	BEAM_REMOVE,
	BEAM_CREATE
}

new const BEAM_COLOR[3] = {0, 255, 0}

new iTrail

public ZmMain_StartRegisterClass()
{
	register_plugin(PLUGIN, VERSION, AUTHOR)
	iMutationClass = g4u_create_zombie_class(CLASS_NAME)
	if (iMutationClass < 0)
		return
		
	g4u_set_class_model(iMutationClass, FIRST_MODEL, SECOND_MODEL, THIRD_MODEL)
	g4u_set_zombie_hand(iMutationClass, MUTATION_FIRST_CLAW_MODEL, MUTATION_SECOND_CLAW_MODEL, MUTATION_THIRD_CLAW_MODEL)
	g4u_set_zombie_hud(iMutationClass, MUTATION_WEAPON_HUD, MUTATION_HUD_CHAR)
	g4u_set_zombie_health(iMutationClass, MUTATION_HEALTH[0], MUTATION_HEALTH[1], MUTATION_HEALTH[2])
	g4u_set_zombie_gravity(iMutationClass, MUTATION_GRAVITY[0], MUTATION_GRAVITY[1], MUTATION_GRAVITY[2])
	g4u_set_zombie_speed(iMutationClass, MUTATION_SPEED[0], MUTATION_SPEED[1], MUTATION_SPEED[2])
	g4u_set_zombie_damage(iMutationClass, MUTATION_DEFENSIVE[0], MUTATION_DEFENSIVE[1], MUTATION_DEFENSIVE[2])
	g4u_set_zombie_sound(iMutationClass, MUTATION_SOUND_DIRECTORY)
	g4u_set_zombie_price(iMutationClass, MUTATION_COST_TYPE, MUTATION_COST)
	g4u_set_zombie_knockback(iMutationClass, MUTATION_KNOCKBACK[0], MUTATION_KNOCKBACK[1], MUTATION_KNOCKBACK[2])
	
	g4u_set_zombie_dmg_armor(iMutationClass, MUTATION_DMG_ARMOR[0], MUTATION_DMG_ARMOR[1], MUTATION_DMG_ARMOR[2])
	g4u_set_zombie_NVG_Option(iMutationClass, MUTATION_NVG_COLOR[0], MUTATION_NVG_COLOR[1], MUTATION_NVG_COLOR[2], MUTATION_NVG_ALPHA, MUTATION_NVG_RADIUS)
	g4u_set_zombie_gender(iMutationClass, MUTATION_GENDER)
	
	RegisterHam(Ham_Spawn, "player", "fw_PlayerRespawn", 1)
	RegisterHam(Ham_Killed, "player", "fw_PlayerKilled", 1)
	
	iTrail = engfunc(EngFunc_PrecacheModel, "sprites/laserbeam.spr")
	
	
}

public plugin_cfg()
{
	if (!g4u_get_zombie_toggle())
	{
		set_fail_state("Can't create Zombie Class because Zombie Mod is OFF")
		return
	}
}

public fw_PlayerRespawn(id)
{
	if (bInSkill[id])
		RemoveBeam(id)

	bInSkill[id] = false
	remove_task(id + TASK_DISABLE_SKILL)
	csred_SetZombieSkillState(id, 0)
}
	
public fw_PlayerKilled(iVictim, iKiller){
	if (bInSkill[iVictim])
	{
		Draw_BarTime(iVictim, 0)
		RemoveBeam(iVictim)
		Engine_SetFOV(iVictim, 90)
	}
	bInSkill[iVictim] = false
	remove_task(iVictim + TASK_DISABLE_SKILL)
	csred_SetZombieSkillState(iVictim, 0)
}

public client_putinserver(id)
{
	if (iHamCz)
		return
		
	if (!is_user_connected(id))
		return
		
	if (!is_user_bot(id))
		return
		
	if (!get_cvar_num("bot_quota"))
		return
		
	set_task(0.1, "RegisterCzFunction", id + TASK_CZ_FUNCTION)
}

public RegisterCzFunction(TASKID)
{
	
	new id = TASKID - TASK_CZ_FUNCTION
	
	if (iHamCz)
		return
		
	if (!is_user_connected(id))
		return
		
	if (!is_user_bot(id))
		return
		
	if (!get_cvar_num("bot_quota"))
		return
		
	RegisterHamFromEntity(Ham_Spawn, id, "fw_PlayerRespawn", 1)
	RegisterHamFromEntity(Ham_Killed, id, "fw_PlayerKilled", 1)
	iHamCz = 1
}

	
public g4u_user_skill_post(id, iClass)
{
	if (!is_user_alive(id))
		return 
		
	if (!g4u_get_user_zombie(id))
		return
		
	if (iClass != iMutationClass)
		return
		
	new iLevel = g4u_get_zombie_level(id) 
	if (iLevel < 2)
		return
		
	if (bInSkill[id])
		return
		
	new iHealth = get_user_health(id) - MUTATION_HEALTH_SKILL
	
	if (!iHealth)
		return
		
	fm_set_user_health(id, iHealth)
	bInSkill[id] = true
	
	if (task_exists(id + TASK_DISABLE_SKILL))
		remove_task(id + TASK_DISABLE_SKILL)
		
	new Float:fTime = float(SKILL_TIME)
	
	set_task(fTime, "fw_DisableSkill", id + TASK_DISABLE_SKILL)
	
	client_cmd(id, "spk %s", MUTATION_SPEED_UP_SOUND)
	
	new Float:fSpeed = csred_get_zombie_speed(id) + 40.0 * g4u_get_zombie_level(id)
	
	set_pev(id, pev_maxspeed, fSpeed)
	Draw_BarTime(id, SKILL_TIME)
	CreateBeam(id, iTrail, 5, 16, BEAM_COLOR[0], BEAM_COLOR[1], BEAM_COLOR[2], 100)
	Engine_SetFOV(id, 110)
	csred_SetZombieSkillState(id, 1)
}

public fw_DisableSkill(TASKID)
{
	new id = TASKID - TASK_DISABLE_SKILL
	
	if (!is_user_alive(id))
		return 
		
	if (!g4u_get_user_zombie(id))
		return
		
	if (g4u_get_zombie_class(id)!= iMutationClass)
		return
		
	if (bInSkill[id])
	{
		
		set_pev(id, pev_maxspeed, csred_get_zombie_speed(id))
		bInSkill[id] = false
		Draw_BarTime(id, 0)
		RemoveBeam(id)
		Engine_SetFOV(id, 90)
	}
	csred_SetZombieSkillState(id, 0)
}


