#if defined _WM_BackWeapon_included
	#endinput
#endif

#define _WM_BackWeapon_included

stock BackWeapon_iSubBody[] =
{
	-1,	// ---
	-1,	// P228
	-1,	// ---
	-1,	// SCOUT
	-1,	// ---
	-1,	// XM1014
	-1,	// ---
	-1,	// MAC10
	-1,	// AUG
	-1,	// ---
	-1,	// ELITE
	-1,	// FIVESEVEN
	-1,	// UMP45
	-1,	// SG550
	-1,	// GALIL
	-1,	// FAMAS
	-1,	// USP
	-1,	// GLOCK18
	-1,	// AWP
	-1,	// MP5NAVY
	-1,	// M249
	-1,	// M3
	-1,	// M4A1
	-1,	// TMP
	-1,	// G3SG1
	-1,	// ---
	-1,	// DEAGLE
	-1,	// SG552
	-1,	// AK47
	-1,	// ---
	-1	// P90
}

stock BackWeapon_szModel[][] =
{
	"models/backweapons.mdl",	// ---
	"models/backweapons.mdl",	// P228
	"models/backweapons.mdl",	// ---
	"models/backweapons.mdl",	// SCOUT
	"models/backweapons.mdl",	// ---
	"models/backweapons.mdl",	// XM1014
	"models/backweapons.mdl",	// ---
	"models/backweapons.mdl",	// MAC10
	"models/backweapons.mdl",	// AUG
	"models/backweapons.mdl",	// ---
	"models/backweapons.mdl",	// ELITE
	"models/backweapons.mdl",	// FIVESEVEN
	"models/backweapons.mdl",	// UMP45
	"models/backweapons.mdl",	// SG550
	"models/backweapons.mdl",	// GALIL
	"models/backweapons.mdl",	// FAMAS
	"models/backweapons.mdl",	// USP
	"models/backweapons.mdl",	// GLOCK18
	"models/backweapons.mdl",	// AWP
	"models/backweapons.mdl",	// MP5NAVY
	"models/backweapons.mdl",	// M249
	"models/backweapons.mdl",	// M3
	"models/backweapons.mdl",	// M4A1
	"models/backweapons.mdl",	// TMP
	"models/backweapons.mdl",	// G3SG1
	"models/backweapons.mdl",	// ---
	"models/backweapons.mdl",	// DEAGLE
	"models/backweapons.mdl",	// SG552
	"models/backweapons.mdl",	// AK47
	"models/backweapons.mdl",	// ---
	"models/backweapons.mdl"	// P90
}