#if defined _WM_COMMAND_included
	#endinput
#endif
#define _WM_COMMAND_included

#define THERMAL_COMMAND	"thermaltoggle"
#define LASER_COMMAND "lasertoggle"
#define SELECTIVE_FIRE_COMMAND "firemodetoggle"
#define DOUBLE_WEAPON_COMMAND	"doubletoggle"


#define PRIM_ARMOURY_CMD "Armoury/Primary"
#define SEC_ARMOURY_CMD "Armoury/Secondary"
#define MELEE_ARMOURY_CMD "Armoury/Melee"
#define GRENADE_ARMOURY_CMD "Armoury/Grenade"
#define DEFAULT_ARMOURY_CMD "Armoury/Default"
