#if defined _cweaponbox_included
  #endinput
#endif
#define _cweaponbox_included

#tryinclude "cstrike_pdatas/cbaseentity_offsets.inc"

// CBaseEntity -> CWeaponBox
// Linux +4
#define XO_CWEAPONBOX 4

//stock const m_rgpPlayerItems_CWeaponBox[6] = { 34 , 35 , ... }
// Usage get_pdata_cbase(weaponbox, m_rgpPlayerItems_CWeaponBox[ 1 ], 4)

//stock const m_rgiszAmmo[32] = { 40 , 41 , ... }
//stock const m_rgAmmo_CWeaponBox[32] = { 72 , 73 , ... }
//#define		m_cAmmoTypes					104
