#if defined _Scoreboard_included
  #endinput
#endif
#define _Scoreboard_included


/*			SCORE BOARD SPRITE			*/

#define SCOREBOARD_SPR_ZM "ScoreBoard/ZombieScore"
#define SCOREBOARD_SPR_ESC "ScoreBoard/ESC_SCORE"
#define SCOREBOARD_SPR_DM "ScoreBoard/DeathMatch-Score"
#define SCOREBOARD_SPR_SM "ScoreBoard/score-single"
#define SCOREBOARD_SPR_GM "ScoreBoard/Ghost-Score"
#define SCOREBOARD_SPR_GG "ScoreBoard/SCOREBOARD_GG"


// --------- TGA SECTION ---------


#define SCOREBOARD_TGA_SM "SCOREBOARD_SM"
#define SCOREBOARD_TGA_DM "SCOREBOARD_DM_TDM"
#define SCOREBOARD_TGA_ZM "SCOREBOARD_ZM"
#define SCOREBOARD_TGA_GM "SCOREBOARD_GM"
#define SCOREBOARD_TGA_ESC "SCOREBOARD_ESC"
#define SCOREBOARD_TGA_GG "SCOREBOARD_GG"

#define HUD_ZM4_BOARD "ScoreBoard/ZM4_ZombieScore"


#define HP_CHANNEL 5
#define AP_CHANNEL 6


#define DISPLAY_TIME 1.2
#define SCOREBOARD_UPDATE_TIME 1.0
#define SCORETEXT_SHOWTIME 1.2


#define MONEY_BOARD "mark/MoneyBoard"

